### ISSUE TITLE
Closed icon in issues again is purple

### ISSUE THREAD

**Issue by krystian3w** [Katsute/GitHub-Red-Closed-Issues-Extension#1]
See:

> ![obraz](https://user-images.githubusercontent.com/35370833/139962113-989c1b46-ab63-4996-84e0-6abf6fc7d4da.png) |
> --- |

My idea for hotfix:

```css
/* issue icon */
   span > svg.octicon-issue-closed {
        color: #F85149 !important;
    }
    .issue-closed-done .TimelineItem-badge[class*="done"] {
        background-color: #F85149 !important;
    }
```

Or try found better.
