### ISSUE TITLE
Pinned closed issues are purple

### ISSUE THREAD

**Issue by krystian3w** [Katsute/GitHub-Red-Closed-Issues-Extension#3]
See these:

https://github.com/FiltersHeroes/KAD/issues (as long nobody unpin my pinned issue)

![obraz](https://user-images.githubusercontent.com/35370833/140809445-b8a5ea77-4f3a-4410-8965-1d60b31748d5.png) |
--- |

my proposition:

```css
.js-pinned-issues-reorder-container .octicon-issue-closed {
        color: var(--rcie-issue-closed) !important;
 }
```

sorry if this is bug on only my PC.
